name: CI and Docker 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc make

    - name: Configure CMake
      run: cmake -B build

    - name: Build Project
      run: cmake --build build

    - name: Run Unit Tests
      run: ./build/unit_tests

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/blazejoz/mini_shell:latest