name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc make

    - name: Configure CMake
      run: cmake -B build

    - name: Build Project
      run: cmake --build build

    - name: Run Unit Tests
      run: ./build/unit_tests